
os:
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install qt5-default qttools5-dev-tools qtmultimedia5-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt5     ; fi

script:
  - cd src
  - /usr/local/opt/qt/bin/qmake
  - make
  - cd ..
  - /usr/local/opt/qt/bin/macdeployqt build/qgo.app

